# config/database.yaml
database:
  host: localhost
  port: 5432
  name: ecommerce
  user: postgres
  password: wrongpassword  # Intentional configuration error
  pool_size: 20
  timeout: 30
  max_connections: 50  # This exceeds pool_size - configuration issue

redis:
  host: localhost
  port: 6379
  timeout: null  # This should be a number - configuration bug
  max_connections: 100

