

# infrastructure/docker-compose.yml
version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:wrongpassword@db:5432/ecommerce
    depends_on:
      - db
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M  # Too low for service requirements
          cpus: '0.5'

  product-service:
    build: ./services/product-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  order-service:
    build: ./services/order-service
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce
    depends_on:
      - db
      - redis
    restart: always

  payment-service:
    build: ./services/payment-service
    ports:
      - "8004:8004"
    environment:
      - STRIPE_API_KEY=  # Missing value - configuration error
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

volumes:
  postgres_data:
